import Constants from 'expo-constants';

const env = Constants.expoConfig?.extra?.env || {};

export default {
  APP_ENV: env.APP_ENV,
  APP_SERVER_API_ROOT: env.APP_SERVER_API_ROOT,
  APP_SERVER_SOCKET_ROOT: env.APP_SERVER_SOCKET_ROOT,
  APP_SERVER_IMAGE_ROOT: env.APP_SERVER_IMAGE_ROOT,
  APP_WEBRTC_TURN_SERVER_IP: env.APP_WEBRTC_TURN_SERVER_IP,
  APP_WEBRTC_TURN_USERNAME: env.APP_WEBRTC_TURN_USERNAME,
  APP_WEBRTC_TURN_CREDENTIAL: env.APP_WEBRTC_TURN_CREDENTIAL,
};
